### ISSUE TITLE
[FEATURE] Re-enable Crop Insurance page

### ISSUE THREAD

**Issue by sandeep-ps** [policy-design-lab/pdl-frontend#130]
**Is your feature request related to a problem? Please describe.**
Currently, the crop insurance page is hidden. It needs to be re-enabled after fixing crop insurance top-line numbers.

**Describe the solution you'd like**
Re-enable the crop insurance page after fixing crop insurance top-line numbers.

**Describe alternatives you've considered**

**Additional context**

**Comment by navarroc** [comment]
This is the task to re-enable crop insurance on the landing page - feel free to do this as part of #121. I just want to capture the task

**Comment by sandeep-ps** [comment]
It would be good to update the CHANGELOG with this issue, even though it might be done as part of a different PR.

**Comment by pengyin-shan** [comment]
In feature 0.5.1. I added this ticket in the 0.5.1 release note and will update the changelog in the PR to merge the main back to dev.

**Comment by pengyin-shan** [comment]
Never mind, this #130 has been added to the 0.5.0 release, so 0.5.1 doesn't need to include this ticket, and no need to do anything when merging the main back to develop branch.
