### ISSUE TITLE
[TASK] Change EQIP to using API

### ISSUE THREAD

**Issue by pengyin-shan** [policy-design-lab/pdl-frontend#132]
## Description
The EQIP page, including the main program and subprograms, are using still using JSON. Switch it to API instead.

## Acceptance Criteria
Everything on the EQIP page must uses API data, all components on the page must function well.

**Comment by ywkim312** [comment]
I am removing good first issue tag since it is not the first issue :) I did the removing json and use api for landing page maps :)
