### ISSUE TITLE
style tweaks

### ISSUE THREAD

**Issue by ziyue5** [policy-design-lab/pdl-frontend#50]
## To-do list
- [x] #51
- [x] #53
- [x] #61
- [x] #62
- [x] #66
- [x] #64
- [x] #55
- [x] #76
- [x] #68
- [x] #80

**Comment by navarroc** [comment]
We should also use a consistent case in the table. Land management Benefit should be LAND MANAGEMENT BENEFIT as shown in the design. Similarly, Structural Benefit should be STRUCTURAL BENEFIT.
