### ISSUE TITLE
Add table of SNAP data to program page

### ISSUE THREAD

**Issue by navarroc** [policy-design-lab/pdl-frontend#59]
SNAP does not have a breakdown of programs like Conservation so we should just display the program data below the SNAP program map. 

Something like:

STATES | SNAP BENEFITS | Avg Monthly Participation | PCT. NATIONWIDE

See the EQIP page for an example of a table layout we can likely re-use a lot of the code. It's the first table that displays providing an overview of EQIP program benefits. I think we want something similar, except for SNAP.

**Comment by navarroc** [comment]
This is a good first/second task after you have reviewed the frontend project code

**Comment by pengyin-shan** [comment]
@navarroc to confirm:

1) this is the table on EQIP that I want to follow the style right?
<img width="1231" alt="Screenshot 2023-03-20 at 10 43 11 AM" src="https://user-images.githubusercontent.com/92752107/226392539-b09f5e6a-b5f1-4174-ac17-41d06446cef6.png">

-----

2) And this is the 'SNAP' section that we want to add the table below (on landing page)? or we are having a SNAP page but it hasn't been pushed to development branch yet?
<img width="1296" alt="Screenshot 2023-03-20 at 10 52 24 AM" src="https://user-images.githubusercontent.com/92752107/226395330-2c7a6ce5-5d36-44e5-9d50-7c602e3060c4.png">

-----

3) For the data using in SNAP table, these are all data files I see in the `data` folder:
<img width="243" alt="Screenshot 2023-03-20 at 10 53 24 AM" src="https://user-images.githubusercontent.com/92752107/226395816-b06a3c7f-7fa5-4adc-875e-40023eed4cf4.png">

Which one should I use for SNAP? Or I'm expected to ask for SNAP data from Yoo Wook or Sandeep?

**Comment by sandeep-ps** [comment]
Hi, Wendy, I'm working on getting this data first. I should be able to share it today. Thanks for your patience.

**Comment by pengyin-shan** [comment]
> Hi, Wendy, I'm working on getting this data first. I should be able to share it today. Thanks for your patience.

great, thanks for updating!

**Comment by pengyin-shan** [comment]
The SNAP page has been merged in the dev branch. Closing this issue
