### ISSUE TITLE
Explore maps of conservation programs should start on overall program page

### ISSUE THREAD

**Issue by navarroc** [policy-design-lab/pdl-frontend#60]
## Expected Behavior
Clicking the explore maps of conservation programs should start on "Total Conservation Programs Benefits" and display the same map as the landing page for the conservation programs. Then, if a user clicks on EQIP: Environmental Quality Incentives Program it should show the EQIP page. 

## Current Behavior
Clicking the explore maps of conservation programs goes directly to EQIP.

**Comment by sandeep-ps** [comment]
Currently, clicking on the "Explore and Clicking on Conservation Programs" button takes the user to the Total Conservation Programs Benefits page. Closing this as a duplicate.
