### ISSUE TITLE
CSP page implementation

### ISSUE THREAD

**Issue by pengyin-shan** [policy-design-lab/pdl-frontend#74]
Develop CSP page using EQIP design in Figma, and add routing to it.

**Comment by pengyin-shan** [comment]
@ziyue5 while I'm going to work on the revisioned version of the SNAP page, do you want to take the CSP page and start soon (since the data is ready)? I'm thinking that I will take the Title I page after SNAP (the data should be ready after I finish the SNAP page). Thus, we can do development at the same time without interrupting each other's code.

**Comment by ziyue5** [comment]
> @ziyue5 while I'm going to work on the revisioned version of the SNAP page, do you want to take the CSP page and start soon (since the data is ready)? I'm thinking that I will take the Title I page after SNAP (the data should be ready after I finish the SNAP page). Thus, we can do development at the same time without interrupting each other's code.

Sounds great! Let's work this way

**Comment by pengyin-shan** [comment]
> 

great, thank you!
